project_id = "farsiai"

[api]
enabled = true

[auth]
enabled = true
site_url = "farsiai://auth"
additional_redirect_urls = ["farsiai://auth/callback"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
